[package]
name = "hinoko-sys"
version = "0.1.0"
description = "FFI bindings for libhinoko0 library"
authors = ["Takashi Sakamoto <o-takashi@sakamocchi.jp>"]
links = "hinoko"
build = "build.rs"
license = "MIT"
repository = "https://github.com/takaswie/hinoko-rs/"

[package.metadata.docs.rs]
features = ["dox"]

[package.metadata.system-deps.hinoko]
name = "hinoko"
version = "0.6"

[lib]
name = "hinoko_sys"

[dependencies]
libc = "0.2"
glib-sys = "0.10"
gobject-sys = "0.10"

[build-dependencies]
pkg-config = "0.3.7"
system-deps = "3"

[dev-dependencies]
shell-words = "0.1.0"
tempfile = "3"

[features]
v0_6 = []
dox = []
