// This file was generated by gir (https://github.com/gtk-rs/gir)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "HinokoFwIsoCtxError", sizeof(HinokoFwIsoCtxError), alignof(HinokoFwIsoCtxError));
    printf("%s;%zu;%zu\n", "HinokoFwIsoCtxInterface", sizeof(HinokoFwIsoCtxInterface), alignof(HinokoFwIsoCtxInterface));
    printf("%s;%zu;%zu\n", "HinokoFwIsoCtxMatchFlag", sizeof(HinokoFwIsoCtxMatchFlag), alignof(HinokoFwIsoCtxMatchFlag));
    printf("%s;%zu;%zu\n", "HinokoFwIsoCtxMode", sizeof(HinokoFwIsoCtxMode), alignof(HinokoFwIsoCtxMode));
    printf("%s;%zu;%zu\n", "HinokoFwIsoIrMultiple", sizeof(HinokoFwIsoIrMultiple), alignof(HinokoFwIsoIrMultiple));
    printf("%s;%zu;%zu\n", "HinokoFwIsoIrMultipleClass", sizeof(HinokoFwIsoIrMultipleClass), alignof(HinokoFwIsoIrMultipleClass));
    printf("%s;%zu;%zu\n", "HinokoFwIsoIrSingle", sizeof(HinokoFwIsoIrSingle), alignof(HinokoFwIsoIrSingle));
    printf("%s;%zu;%zu\n", "HinokoFwIsoIrSingleClass", sizeof(HinokoFwIsoIrSingleClass), alignof(HinokoFwIsoIrSingleClass));
    printf("%s;%zu;%zu\n", "HinokoFwIsoIt", sizeof(HinokoFwIsoIt), alignof(HinokoFwIsoIt));
    printf("%s;%zu;%zu\n", "HinokoFwIsoItClass", sizeof(HinokoFwIsoItClass), alignof(HinokoFwIsoItClass));
    printf("%s;%zu;%zu\n", "HinokoFwIsoResourceAuto", sizeof(HinokoFwIsoResourceAuto), alignof(HinokoFwIsoResourceAuto));
    printf("%s;%zu;%zu\n", "HinokoFwIsoResourceAutoClass", sizeof(HinokoFwIsoResourceAutoClass), alignof(HinokoFwIsoResourceAutoClass));
    printf("%s;%zu;%zu\n", "HinokoFwIsoResourceAutoError", sizeof(HinokoFwIsoResourceAutoError), alignof(HinokoFwIsoResourceAutoError));
    printf("%s;%zu;%zu\n", "HinokoFwIsoResourceError", sizeof(HinokoFwIsoResourceError), alignof(HinokoFwIsoResourceError));
    printf("%s;%zu;%zu\n", "HinokoFwIsoResourceInterface", sizeof(HinokoFwIsoResourceInterface), alignof(HinokoFwIsoResourceInterface));
    printf("%s;%zu;%zu\n", "HinokoFwIsoResourceOnce", sizeof(HinokoFwIsoResourceOnce), alignof(HinokoFwIsoResourceOnce));
    printf("%s;%zu;%zu\n", "HinokoFwIsoResourceOnceClass", sizeof(HinokoFwIsoResourceOnceClass), alignof(HinokoFwIsoResourceOnceClass));
    printf("%s;%zu;%zu\n", "HinokoFwScode", sizeof(HinokoFwScode), alignof(HinokoFwScode));
    return 0;
}
