// Feel free to edit this file, it won't be regenerated by gir generator unless removed.
#include <hinoko-0.0/cycle_timer.h>
#include <hinoko-0.0/fw_iso_ctx.h>
#include <hinoko-0.0/fw_iso_resource.h>
#include <hinoko-0.0/fw_iso_resource_auto.h>
#include <hinoko-0.0/fw_iso_rx_multiple.h>
#include <hinoko-0.0/fw_iso_rx_single.h>
#include <hinoko-0.0/fw_iso_tx.h>
#include <hinoko-0.0/hinoko_enum_types.h>
#include <hinoko-0.0/hinoko_enums.h>
