[options]
girs_directories = ["../../gir-files", "../.."]
work_mode = "sys"
library = "Hinoko"
version = "1.0"
min_cfg_version = "1.0"
single_version_file = "."
external_libraries = [
  "GLib",
  "GObject",
  "Hinawa",
]
