[package]
name = "hinoko"
version = "0.1.0"
description = "API bindings for libhinoko0 library"
authors = ["Takashi Sakamoto <o-takashi@sakamocchi.jp>"]
license = "MIT"
repository = "https://github.com/takaswie/hinoko-rs/"

[lib]
name = "hinoko"

[dependencies]
libc = "0.2"
bitflags = "1.0"
glib = "0.10"
glib-sys = "0.10"
gobject-sys = "0.10"
hinoko-sys = { path = "../hinoko-sys", version = "0.1" }

[dev-dependencies]
gir-format-check = "^0.1"
