[package]
name = "hinoko"
version = "0.0.1"
authors = ["Takashi Sakamoto <o-takashi@sakamocchi.jp>"]

[lib]
name = "hinoko"

[dependencies]
libc = "0.2"
bitflags = "1.0"
glib = { git = "https://github.com/gtk-rs/glib" }
glib-sys = { git = "https://github.com/gtk-rs/sys" }
gobject-sys = { git = "https://github.com/gtk-rs/sys" }
hinoko-sys = { path = "../hinoko-sys" }

[dev-dependencies]
gir-format-check = "^0.1"
