[options]
girs_directories = ["../gir-files", ".."]
work_mode = "normal"
library = "Hinoko"
version = "0.0"
use_gi_docgen = true
min_cfg_version = "0.7"
single_version_file = true

generate = [
    "Hinoko.FwIsoCtxMode",
    "Hinoko.FwScode",
    "Hinoko.FwIsoCtxMatchFlag",
    "Hinoko.FwIsoResource",
    "Hinoko.FwIsoResourceAuto",
    "Hinoko.FwIsoResourceOnce",
    "Hinoko.FwIsoCtxError",
    "Hinoko.FwIsoResourceError",
    "Hinoko.FwIsoResourceAutoError",
]

manual = [
    "GLib.Error",
    "GLib.Source",
    "GLib.ByteArray",
]

[[object]]
name = "Hinoko.CycleTimer"
status = "generate"
concurrency = "send"
    [[object.function]]
    name = "get_cycle_timer"
    manual = true

[[object]]
name = "Hinoko.FwIsoCtx"
status = "generate"
manual_traits = ["FwIsoCtxExtManual"]
    [[object.function]]
    name = "get_cycle_timer"
    manual = true
    doc_trait_name = "FwIsoCtxExtManual"

[[object]]
name = "Hinoko.FwIsoRxSingle"
status = "generate"
manual_traits = ["FwIsoRxSingleExtManual"]
    [[object.function]]
    name = "start"
    manual = true
    doc_trait_name = "FwIsoRxSingleExtManual"
    [[object.function]]
    name = "get_payload"
    manual = true
    doc_trait_name = "FwIsoRxSingleExtManual"
    [[object.signal]]
    name = "interrupted"
    manual = true
    doc_trait_name = "FwIsoRxSingleExtManual"

[[object]]
name = "Hinoko.FwIsoRxMultiple"
status = "generate"
manual_traits = ["FwIsoRxMultipleExtManual"]
    [[object.property]]
    name = "channels"
    manual = true
    doc_trait_name = "FwIsoRxMultipleExtManual"
    [[object.function]]
    name = "start"
    manual = true
    doc_trait_name = "FwIsoRxMultipleExtManual"
    [[object.function]]
    name = "get_payload"
    manual = true
    doc_trait_name = "FwIsoRxMultipleExtManual"

[[object]]
name = "Hinoko.FwIsoTx"
status = "generate"
manual_traits = ["FwIsoTxExtManual"]
    [[object.function]]
    name = "register_packet"
    manual = true
    doc_trait_name = "FwIsoTxExtManual"
    [[object.function]]
    name = "start"
    manual = true
    doc_trait_name = "FwIsoTxExtManual"
    [[object.signal]]
    name = "interrupted"
    manual = true
    doc_trait_name = "FwIsoTxExtManual"
