[options]
girs_directories = ["../gir-files", ".."]
work_mode = "normal"
library = "Hinoko"
version = "0.0"
use_gi_docgen = true
min_cfg_version = "0.9"
single_version_file = true

generate = [
    "Hinoko.FwIsoCtxMode",
    "Hinoko.FwScode",
    "Hinoko.FwIsoCtxMatchFlag",
    "Hinoko.FwIsoResource",
    "Hinoko.FwIsoResourceAuto",
    "Hinoko.FwIsoResourceOnce",
    "Hinoko.FwIsoCtxError",
    "Hinoko.FwIsoResourceError",
    "Hinoko.FwIsoResourceAutoError",
]

manual = [
    "GLib.Error",
    "GLib.Source",
    "GLib.ByteArray",
    "Hinawa.CycleTime",
]

[[object]]
name = "Hinoko.FwIsoCtx"
status = "generate"
manual_traits = ["FwIsoCtxExtManual"]
    [[object.function]]
    name = "read_cycle_time"
    manual = true
    doc_trait_name = "FwIsoCtxExtManual"

[[object]]
name = "Hinoko.FwIsoIrSingle"
status = "generate"
manual_traits = ["FwIsoIrSingleExtManual"]
    [[object.function]]
    name = "start"
    manual = true
    doc_trait_name = "FwIsoIrSingleExtManual"
    [[object.function]]
    name = "get_payload"
    manual = true
    doc_trait_name = "FwIsoIrSingleExtManual"
    [[object.signal]]
    name = "interrupted"
    manual = true
    doc_trait_name = "FwIsoIrSingleExtManual"

[[object]]
name = "Hinoko.FwIsoIrMultiple"
status = "generate"
manual_traits = ["FwIsoIrMultipleExtManual"]
    [[object.property]]
    name = "channels"
    manual = true
    doc_trait_name = "FwIsoIrMultipleExtManual"
    [[object.function]]
    name = "start"
    manual = true
    doc_trait_name = "FwIsoIrMultipleExtManual"
    [[object.function]]
    name = "get_payload"
    manual = true
    doc_trait_name = "FwIsoIrMultipleExtManual"

[[object]]
name = "Hinoko.FwIsoIt"
status = "generate"
manual_traits = ["FwIsoItExtManual"]
    [[object.function]]
    name = "register_packet"
    manual = true
    doc_trait_name = "FwIsoItExtManual"
    [[object.function]]
    name = "start"
    manual = true
    doc_trait_name = "FwIsoItExtManual"
    [[object.signal]]
    name = "interrupted"
    manual = true
    doc_trait_name = "FwIsoItExtManual"
