// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::FwScode;
use glib::object::Cast;
use glib::object::IsA;
use glib::signal::connect_raw;
use glib::signal::SignalHandlerId;
use glib::translate::*;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;
use std::ptr;

glib::wrapper! {
    #[doc(alias = "HinokoFwIsoResource")]
    pub struct FwIsoResource(Object<ffi::HinokoFwIsoResource, ffi::HinokoFwIsoResourceClass>);

    match fn {
        type_ => || ffi::hinoko_fw_iso_resource_get_type(),
    }
}

impl FwIsoResource {
    pub const NONE: Option<&'static FwIsoResource> = None;

    #[doc(alias = "hinoko_fw_iso_resource_new")]
    pub fn new() -> FwIsoResource {
        unsafe { from_glib_full(ffi::hinoko_fw_iso_resource_new()) }
    }

    #[doc(alias = "hinoko_fw_iso_resource_calculate_bandwidth")]
    pub fn calculate_bandwidth(bytes_per_payload: u32, scode: FwScode) -> u32 {
        unsafe {
            ffi::hinoko_fw_iso_resource_calculate_bandwidth(bytes_per_payload, scode.into_glib())
        }
    }
}

impl Default for FwIsoResource {
    fn default() -> Self {
        Self::new()
    }
}

pub trait FwIsoResourceExt: 'static {
    #[doc(alias = "hinoko_fw_iso_resource_allocate_once_async")]
    fn allocate_once_async(
        &self,
        channel_candidates: &[u8],
        bandwidth: u32,
    ) -> Result<(), glib::Error>;

    #[doc(alias = "hinoko_fw_iso_resource_allocate_once_sync")]
    fn allocate_once_sync(
        &self,
        channel_candidates: &[u8],
        bandwidth: u32,
    ) -> Result<(), glib::Error>;

    #[doc(alias = "hinoko_fw_iso_resource_create_source")]
    fn create_source(&self) -> Result<glib::Source, glib::Error>;

    #[doc(alias = "hinoko_fw_iso_resource_deallocate_once_async")]
    fn deallocate_once_async(&self, channel: u32, bandwidth: u32) -> Result<(), glib::Error>;

    #[doc(alias = "hinoko_fw_iso_resource_deallocate_once_sync")]
    fn deallocate_once_sync(&self, channel: u32, bandwidth: u32) -> Result<(), glib::Error>;

    #[doc(alias = "hinoko_fw_iso_resource_open")]
    fn open(&self, path: &str, open_flag: i32) -> Result<(), glib::Error>;

    #[doc(alias = "allocated")]
    fn connect_allocated<F: Fn(&Self, u32, u32, &glib::Error) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId;

    #[doc(alias = "deallocated")]
    fn connect_deallocated<F: Fn(&Self, u32, u32, &glib::Error) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId;
}

impl<O: IsA<FwIsoResource>> FwIsoResourceExt for O {
    fn allocate_once_async(
        &self,
        channel_candidates: &[u8],
        bandwidth: u32,
    ) -> Result<(), glib::Error> {
        let channel_candidates_count = channel_candidates.len() as usize;
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::hinoko_fw_iso_resource_allocate_once_async(
                self.as_ref().to_glib_none().0,
                channel_candidates.to_glib_none().0,
                channel_candidates_count,
                bandwidth,
                &mut error,
            );
            if error.is_null() {
                Ok(())
            } else {
                Err(from_glib_full(error))
            }
        }
    }

    fn allocate_once_sync(
        &self,
        channel_candidates: &[u8],
        bandwidth: u32,
    ) -> Result<(), glib::Error> {
        let channel_candidates_count = channel_candidates.len() as usize;
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::hinoko_fw_iso_resource_allocate_once_sync(
                self.as_ref().to_glib_none().0,
                channel_candidates.to_glib_none().0,
                channel_candidates_count,
                bandwidth,
                &mut error,
            );
            if error.is_null() {
                Ok(())
            } else {
                Err(from_glib_full(error))
            }
        }
    }

    fn create_source(&self) -> Result<glib::Source, glib::Error> {
        unsafe {
            let mut gsrc = ptr::null_mut();
            let mut error = ptr::null_mut();
            let _ = ffi::hinoko_fw_iso_resource_create_source(
                self.as_ref().to_glib_none().0,
                &mut gsrc,
                &mut error,
            );
            if error.is_null() {
                Ok(from_glib_full(gsrc))
            } else {
                Err(from_glib_full(error))
            }
        }
    }

    fn deallocate_once_async(&self, channel: u32, bandwidth: u32) -> Result<(), glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::hinoko_fw_iso_resource_deallocate_once_async(
                self.as_ref().to_glib_none().0,
                channel,
                bandwidth,
                &mut error,
            );
            if error.is_null() {
                Ok(())
            } else {
                Err(from_glib_full(error))
            }
        }
    }

    fn deallocate_once_sync(&self, channel: u32, bandwidth: u32) -> Result<(), glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::hinoko_fw_iso_resource_deallocate_once_sync(
                self.as_ref().to_glib_none().0,
                channel,
                bandwidth,
                &mut error,
            );
            if error.is_null() {
                Ok(())
            } else {
                Err(from_glib_full(error))
            }
        }
    }

    fn open(&self, path: &str, open_flag: i32) -> Result<(), glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::hinoko_fw_iso_resource_open(
                self.as_ref().to_glib_none().0,
                path.to_glib_none().0,
                open_flag,
                &mut error,
            );
            if error.is_null() {
                Ok(())
            } else {
                Err(from_glib_full(error))
            }
        }
    }

    fn connect_allocated<F: Fn(&Self, u32, u32, &glib::Error) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId {
        unsafe extern "C" fn allocated_trampoline<
            P: IsA<FwIsoResource>,
            F: Fn(&P, u32, u32, &glib::Error) + 'static,
        >(
            this: *mut ffi::HinokoFwIsoResource,
            channel: libc::c_uint,
            bandwidth: libc::c_uint,
            error: *mut glib::ffi::GError,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(
                FwIsoResource::from_glib_borrow(this).unsafe_cast_ref(),
                channel,
                bandwidth,
                &from_glib_borrow(error),
            )
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"allocated\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    allocated_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_deallocated<F: Fn(&Self, u32, u32, &glib::Error) + 'static>(
        &self,
        f: F,
    ) -> SignalHandlerId {
        unsafe extern "C" fn deallocated_trampoline<
            P: IsA<FwIsoResource>,
            F: Fn(&P, u32, u32, &glib::Error) + 'static,
        >(
            this: *mut ffi::HinokoFwIsoResource,
            channel: libc::c_uint,
            bandwidth: libc::c_uint,
            error: *mut glib::ffi::GError,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(
                FwIsoResource::from_glib_borrow(this).unsafe_cast_ref(),
                channel,
                bandwidth,
                &from_glib_borrow(error),
            )
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"deallocated\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    deallocated_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl fmt::Display for FwIsoResource {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("FwIsoResource")
    }
}
