// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::FwIsoResource;
use glib::object::IsA;
use glib::translate::*;
use std::fmt;
use std::ptr;

glib::wrapper! {
    #[doc(alias = "HinokoFwIsoResourceOnce")]
    pub struct FwIsoResourceOnce(Object<ffi::HinokoFwIsoResourceOnce, ffi::HinokoFwIsoResourceOnceClass>) @implements FwIsoResource;

    match fn {
        type_ => || ffi::hinoko_fw_iso_resource_once_get_type(),
    }
}

impl FwIsoResourceOnce {
    pub const NONE: Option<&'static FwIsoResourceOnce> = None;

    #[doc(alias = "hinoko_fw_iso_resource_once_new")]
    pub fn new() -> FwIsoResourceOnce {
        unsafe { from_glib_full(ffi::hinoko_fw_iso_resource_once_new()) }
    }
}

impl Default for FwIsoResourceOnce {
    fn default() -> Self {
        Self::new()
    }
}

pub trait FwIsoResourceOnceExt: 'static {
    #[doc(alias = "hinoko_fw_iso_resource_once_deallocate_async")]
    fn deallocate_async(&self, channel: u32, bandwidth: u32) -> Result<(), glib::Error>;

    #[doc(alias = "hinoko_fw_iso_resource_once_deallocate_sync")]
    fn deallocate_sync(
        &self,
        channel: u32,
        bandwidth: u32,
        timeout_ms: u32,
    ) -> Result<(), glib::Error>;
}

impl<O: IsA<FwIsoResourceOnce>> FwIsoResourceOnceExt for O {
    fn deallocate_async(&self, channel: u32, bandwidth: u32) -> Result<(), glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let is_ok = ffi::hinoko_fw_iso_resource_once_deallocate_async(
                self.as_ref().to_glib_none().0,
                channel,
                bandwidth,
                &mut error,
            );
            assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
            if error.is_null() {
                Ok(())
            } else {
                Err(from_glib_full(error))
            }
        }
    }

    fn deallocate_sync(
        &self,
        channel: u32,
        bandwidth: u32,
        timeout_ms: u32,
    ) -> Result<(), glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let is_ok = ffi::hinoko_fw_iso_resource_once_deallocate_sync(
                self.as_ref().to_glib_none().0,
                channel,
                bandwidth,
                timeout_ms,
                &mut error,
            );
            assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
            if error.is_null() {
                Ok(())
            } else {
                Err(from_glib_full(error))
            }
        }
    }
}

impl fmt::Display for FwIsoResourceOnce {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("FwIsoResourceOnce")
    }
}
